/*
 * Spotify
 * Simple API for advanced programming course, Dr. Mojtaba Vahidi Asl, Fall 1400 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nima.heydari79@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2005
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-05T21:49:04.736Z[GMT]")
public class InlineResponse2005 {
  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("premium_until")
  private String premiumUntil = null;

  public InlineResponse2005 success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @Schema(required = true, description = "")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public InlineResponse2005 premiumUntil(String premiumUntil) {
    this.premiumUntil = premiumUntil;
    return this;
  }

   /**
   * Get premiumUntil
   * @return premiumUntil
  **/
  @Schema(required = true, description = "")
  public String getPremiumUntil() {
    return premiumUntil;
  }

  public void setPremiumUntil(String premiumUntil) {
    this.premiumUntil = premiumUntil;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.success, inlineResponse2005.success) &&
        Objects.equals(this.premiumUntil, inlineResponse2005.premiumUntil);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, premiumUntil);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    premiumUntil: ").append(toIndentedString(premiumUntil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
