/*
 * Spotify
 * Simple API for advanced programming course, Dr. Mojtaba Vahidi Asl, Fall 1400 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nima.heydari79@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthLoginBody;
import io.swagger.client.model.AuthSignupBody;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Login
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        AuthLoginBody body = null;
        InlineResponse2002 response = api.login(body);

        // TODO: test validations
    }
    /**
     * Sign Up
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signUpTest() throws ApiException {
        AuthSignupBody body = null;
        InlineResponse2002 response = api.signUp(body);

        // TODO: test validations
    }
}
